### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#280]
- [x] Create a branch for the release. **`release-v1.2.0`**
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with `npm`. **Done in #281**
- [x] Do a test build of the NPM package on your local machine so you know if something is going off the rails before the automated build action on GitHub. **Done as part of #281**
- [x] Bump the `"version"` number in `package.json` and reinstall the dependencies so the correct version number is in `package-lock.json`. **Done in commit 637e1dea2b8cabdd5820e5f91fa9a9512749ef8a**
- [x] Open a PR that merges the release branch into main. **See #282**
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated NPM package build on GitHub. If the package build succeeds it will be automatically published to NPM.

**Comment by alancleary** [comment]
v1.2.0 successfully released!
